package sync

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/shuiyu486/re-context-kits/internal/rekit/casebind"
)

// ExclusiveInitRetirementMode distinguishes the first, complete-tree
// inspection from recovery after an interrupted retirement.
type ExclusiveInitRetirementMode string

const (
	// ExclusiveInitRetirementFirst requires every planned leaf and directory.
	ExclusiveInitRetirementFirst ExclusiveInitRetirementMode = "first"
	// ExclusiveInitRetirementResume accepts an exact planned subset or an absent root.
	ExclusiveInitRetirementResume ExclusiveInitRetirementMode = "resume"
)

// ExclusiveInitRetirementLeaf is the compact exact-content binding retained
// from an exclusive initialization write.
type ExclusiveInitRetirementLeaf struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

// ExclusiveInitRetirementPlan is the compact owner-level description of one
// generated tree. Directories are derived deterministically from Leaves.
type ExclusiveInitRetirementPlan struct {
	SchemaVersion int                           `json:"schemaVersion"`
	Command       string                        `json:"command"`
	CaseRoot      string                        `json:"caseRoot"`
	ProvisionID   string                        `json:"provisionId"`
	Role          string                        `json:"role"`
	Leaves        []ExclusiveInitRetirementLeaf `json:"leaves"`
}

// ExclusiveInitRetirementRootInspection reports the exact planned objects
// that remain under one root.
type ExclusiveInitRetirementRootInspection struct {
	CaseRoot             string `json:"caseRoot"`
	Present              bool   `json:"present"`
	PlannedLeaves        int    `json:"plannedLeaves"`
	PlannedDirectories   int    `json:"plannedDirectories"`
	RemainingLeaves      int    `json:"remainingLeaves"`
	RemainingDirectories int    `json:"remainingDirectories"`
	RemainingRoots       int    `json:"remainingRoots"`
}

// ExclusiveInitRetirementInspection is a read-only, batch-wide preflight.
type ExclusiveInitRetirementInspection struct {
	SchemaVersion        int                                     `json:"schemaVersion"`
	Command              string                                  `json:"command"`
	Mode                 ExclusiveInitRetirementMode             `json:"mode"`
	Roots                []ExclusiveInitRetirementRootInspection `json:"roots"`
	CommonParent         string                                  `json:"commonParent,omitempty"`
	CommonParentIdentity bool                                    `json:"commonParentIdentity"`
	RemainingLeaves      int                                     `json:"remainingLeaves"`
	RemainingDirectories int                                     `json:"remainingDirectories"`
	RemainingRoots       int                                     `json:"remainingRoots"`
}

// ExclusiveInitRetirementResult reports deterministic removals and confirms
// that no planned objects remain after a successful batch apply.
type ExclusiveInitRetirementResult struct {
	SchemaVersion        int                                     `json:"schemaVersion"`
	Command              string                                  `json:"command"`
	Mode                 ExclusiveInitRetirementMode             `json:"mode"`
	Applied              bool                                    `json:"applied"`
	Roots                []ExclusiveInitRetirementRootInspection `json:"roots"`
	RemovedLeaves        int                                     `json:"removedLeaves"`
	RemovedDirectories   int                                     `json:"removedDirectories"`
	RemovedRoots         int                                     `json:"removedRoots"`
	RemainingLeaves      int                                     `json:"remainingLeaves"`
	RemainingDirectories int                                     `json:"remainingDirectories"`
	RemainingRoots       int                                     `json:"remainingRoots"`
}

// These package-private hooks are deterministic test seams. Production leaves
// them nil.
var (
	exclusiveInitRetirementAfterPreflightHook func() error
	exclusiveInitRetirementRemoveHook         func(stage, caseRoot, rel string) error
)

// BuildExclusiveInitRetirementPlan drops generated bytes and unrelated init
// metadata while preserving the exact root, owner, path, size, and hash bindings.
func BuildExclusiveInitRetirementPlan(plan ExclusiveInitPlan) (ExclusiveInitRetirementPlan, error) {
	if err := validateExclusiveInitPlan(plan); err != nil {
		return ExclusiveInitRetirementPlan{}, err
	}
	leaves := make([]ExclusiveInitRetirementLeaf, 0, len(plan.Writes))
	for _, write := range plan.Writes {
		leaves = append(leaves, ExclusiveInitRetirementLeaf{Path: write.Path, SHA256: write.SHA256, Size: write.Size})
	}
	sort.Slice(leaves, func(i, j int) bool { return leaves[i].Path < leaves[j].Path })
	return ExclusiveInitRetirementPlan{
		SchemaVersion: 1,
		Command:       "exclusive-init-retirement",
		CaseRoot:      plan.CaseRoot,
		ProvisionID:   plan.ProvisionID,
		Role:          plan.Role,
		Leaves:        leaves,
	}, nil
}

// InspectExclusiveInitRetirementBatch performs one unified read-only preflight.
// First mode requires complete exact trees; resume mode permits only exact
// planned subsets or absent roots.
func InspectExclusiveInitRetirementBatch(mode ExclusiveInitRetirementMode, plans ...ExclusiveInitRetirementPlan) (ExclusiveInitRetirementInspection, error) {
	batch, err := prepareExclusiveInitRetirementBatch(mode, plans)
	if err != nil {
		return ExclusiveInitRetirementInspection{}, err
	}
	inspection := batch.inspection()
	return inspection, batch.close()
}

// ApplyExclusiveInitRetirementBatch preflights every root before deleting any
// object, then removes leaves, directories, and roots in deterministic
// bottom-up order without RemoveAll. Retry an interrupted first apply in resume
// mode.
func ApplyExclusiveInitRetirementBatch(mode ExclusiveInitRetirementMode, plans ...ExclusiveInitRetirementPlan) (ExclusiveInitRetirementResult, error) {
	batch, err := prepareExclusiveInitRetirementBatch(mode, plans)
	if err != nil {
		return ExclusiveInitRetirementResult{}, err
	}
	defer batch.close()
	return applyExclusiveInitRetirementPreparedBatch(batch)
}

// ApplyExclusiveInitRetirementBatchBoundToParent prepares and pins every root,
// requires all direct root parents to share expectedParent's filesystem
// identity, and applies on those same handles without reopening the namespace.
func ApplyExclusiveInitRetirementBatchBoundToParent(mode ExclusiveInitRetirementMode, expectedParent os.FileInfo, plans ...ExclusiveInitRetirementPlan) (ExclusiveInitRetirementResult, error) {
	if expectedParent == nil || !expectedParent.IsDir() {
		return ExclusiveInitRetirementResult{}, fmt.Errorf("exclusive init retirement expected parent is not a directory")
	}
	batch, err := prepareExclusiveInitRetirementBatch(mode, plans)
	if err != nil {
		return ExclusiveInitRetirementResult{}, err
	}
	defer batch.close()
	if err := batch.bindCommonParent(expectedParent); err != nil {
		return ExclusiveInitRetirementResult{}, err
	}
	return applyExclusiveInitRetirementPreparedBatch(batch)
}

func applyExclusiveInitRetirementPreparedBatch(batch *exclusiveInitRetirementBatch) (ExclusiveInitRetirementResult, error) {
	mode := batch.mode
	before := batch.inspection()
	result := ExclusiveInitRetirementResult{
		SchemaVersion:        1,
		Command:              "exclusive-init-retirement",
		Mode:                 mode,
		Roots:                append([]ExclusiveInitRetirementRootInspection(nil), before.Roots...),
		RemainingLeaves:      before.RemainingLeaves,
		RemainingDirectories: before.RemainingDirectories,
		RemainingRoots:       before.RemainingRoots,
	}
	if exclusiveInitRetirementAfterPreflightHook != nil {
		if err := exclusiveInitRetirementAfterPreflightHook(); err != nil {
			return result, err
		}
	}
	// Revalidate the complete batch after the test seam and immediately before
	// the first mutation. A later-root error therefore cannot partially retire an
	// earlier root.
	if err := batch.revalidate(); err != nil {
		return result, err
	}

	for i := range batch.roots {
		root := &batch.roots[i]
		if !root.status.Present {
			if root.absentBoundary != "" {
				if _, err := root.parent.Lstat(root.absentBoundary); !os.IsNotExist(err) {
					return result, fmt.Errorf("exclusive init retirement absent boundary rebound: %s", root.plan.CaseRoot)
				}
			} else {
				canonical := filepath.Base(root.plan.CaseRoot)
				if _, err := root.parent.Lstat(canonical); !os.IsNotExist(err) {
					return result, fmt.Errorf("exclusive init retirement absent root rebound: %s", root.plan.CaseRoot)
				}
				if _, err := root.parent.Lstat(root.rootQuarantine); !os.IsNotExist(err) {
					return result, fmt.Errorf("exclusive init retirement absent root quarantine rebound: %s", root.plan.CaseRoot)
				}
			}
			continue
		}
		for _, leaf := range root.plan.Leaves {
			info, canonicalPresent := root.leafInfos[leaf.Path]
			quarantineInfo, quarantinePresent := root.leafQuarantineInfos[leaf.Path]
			if canonicalPresent && quarantinePresent {
				return result, fmt.Errorf("exclusive init retirement leaf and owned quarantine both exist: %s", leaf.Path)
			}
			if !canonicalPresent && !quarantinePresent {
				continue
			}
			if err := validateExclusiveInitRetirementRootBinding(root); err != nil {
				return result, err
			}
			if canonicalPresent && exclusiveInitRetirementRemoveHook != nil {
				if err := verifyExclusiveInitRetirementLeaf(root.root, leaf, info); err != nil {
					return result, err
				}
				if err := exclusiveInitRetirementRemoveHook("before-leaf", root.plan.CaseRoot, leaf.Path); err != nil {
					return result, err
				}
			}
			if err := validateExclusiveInitRetirementRootBinding(root); err != nil {
				return result, err
			}
			if err := retireExclusiveInitRetirementLeaf(root.root, leaf, info, quarantineInfo, root.plan.CaseRoot); err != nil {
				return result, err
			}
			delete(root.leafInfos, leaf.Path)
			delete(root.leafQuarantineInfos, leaf.Path)
			root.status.RemainingLeaves--
			result.Roots[i].RemainingLeaves--
			result.RemovedLeaves++
			result.RemainingLeaves--
		}
		for _, dir := range root.directories {
			info, canonicalPresent := root.dirInfos[dir]
			quarantineInfo, quarantinePresent := root.dirQuarantineInfos[dir]
			if canonicalPresent && quarantinePresent {
				return result, fmt.Errorf("exclusive init retirement directory and owned quarantine both exist: %s", dir)
			}
			if !canonicalPresent && !quarantinePresent {
				continue
			}
			if canonicalPresent {
				current, err := root.root.Lstat(filepath.FromSlash(dir))
				if err != nil || current.Mode()&os.ModeSymlink != 0 || !current.IsDir() || !os.SameFile(info, current) {
					return result, fmt.Errorf("exclusive init retirement directory identity changed: %s", dir)
				}
				if exclusiveInitRetirementRemoveHook != nil {
					if err := exclusiveInitRetirementRemoveHook("before-directory", root.plan.CaseRoot, dir); err != nil {
						return result, err
					}
				}
			}
			if err := retireExclusiveInitRetirementDirectory(root.root, dir, info, quarantineInfo, root.plan); err != nil {
				return result, err
			}
			delete(root.dirInfos, dir)
			delete(root.dirQuarantineInfos, dir)
			root.status.RemainingDirectories--
			result.Roots[i].RemainingDirectories--
			result.RemovedDirectories++
			result.RemainingDirectories--
		}
		if err := validateExclusiveInitRetirementRootBinding(root); err != nil {
			return result, err
		}
		if exclusiveInitRetirementRemoveHook != nil {
			if err := exclusiveInitRetirementRemoveHook("before-root", root.plan.CaseRoot, "."); err != nil {
				return result, err
			}
		}
		if err := validateExclusiveInitRetirementRootBinding(root); err != nil {
			return result, err
		}
		if err := quarantineExclusiveInitRetirementRoot(root); err != nil {
			return result, err
		}
		root.status.Present = false
		root.status.RemainingRoots = 0
		result.Roots[i].Present = false
		result.Roots[i].RemainingRoots = 0
		result.RemovedRoots++
		result.RemainingRoots--
	}
	for i := range result.Roots {
		result.Roots[i].Present = false
		result.Roots[i].RemainingLeaves = 0
		result.Roots[i].RemainingDirectories = 0
		result.Roots[i].RemainingRoots = 0
	}
	result.Applied = true
	return result, nil
}

type exclusiveInitRetirementRoot struct {
	plan                ExclusiveInitRetirementPlan
	parent              *os.Root
	root                *os.Root
	rootName            string
	rootQuarantine      string
	rootInfo            os.FileInfo
	rootQuarantined     bool
	absentBoundary      string
	directories         []string
	leafInfos           map[string]os.FileInfo
	leafQuarantineInfos map[string]os.FileInfo
	dirInfos            map[string]os.FileInfo
	dirQuarantineInfos  map[string]os.FileInfo
	status              ExclusiveInitRetirementRootInspection
}

type exclusiveInitRetirementBatch struct {
	mode  ExclusiveInitRetirementMode
	roots []exclusiveInitRetirementRoot
}

func prepareExclusiveInitRetirementBatch(mode ExclusiveInitRetirementMode, input []ExclusiveInitRetirementPlan) (*exclusiveInitRetirementBatch, error) {
	if mode != ExclusiveInitRetirementFirst && mode != ExclusiveInitRetirementResume {
		return nil, fmt.Errorf("invalid exclusive init retirement mode: %q", mode)
	}
	if len(input) == 0 {
		return nil, fmt.Errorf("exclusive init retirement batch has no plans")
	}
	batch := &exclusiveInitRetirementBatch{mode: mode, roots: make([]exclusiveInitRetirementRoot, len(input))}
	seen := map[string]struct{}{}
	for i, original := range input {
		plan, directories, err := normalizeExclusiveInitRetirementPlan(original)
		if err != nil {
			batch.close()
			return nil, err
		}
		key := strings.ToLower(filepath.Clean(plan.CaseRoot))
		for other := range seen {
			if exclusiveInitRetirementRootsOverlap(key, other) {
				batch.close()
				return nil, fmt.Errorf("exclusive init retirement batch has overlapping roots: %s", plan.CaseRoot)
			}
		}
		seen[key] = struct{}{}
		item := &batch.roots[i]
		item.plan = plan
		item.directories = directories
		item.rootName = filepath.Base(plan.CaseRoot)
		item.rootQuarantine = exclusiveInitRetirementRootQuarantineName(item.rootName, plan)
		item.status = ExclusiveInitRetirementRootInspection{
			CaseRoot:           plan.CaseRoot,
			PlannedLeaves:      len(plan.Leaves),
			PlannedDirectories: len(directories),
		}
		item.parent, item.rootName, item.absentBoundary, err = openExclusiveInitRetirementParent(plan.CaseRoot, mode)
		if err != nil {
			batch.close()
			return nil, err
		}
		info, err := item.parent.Lstat(item.rootName)
		quarantineInfo, quarantineErr := item.parent.Lstat(item.rootQuarantine)
		canonicalPresent := err == nil
		quarantinePresent := quarantineErr == nil
		if err != nil && !os.IsNotExist(err) {
			batch.close()
			return nil, err
		}
		if quarantineErr != nil && !os.IsNotExist(quarantineErr) {
			batch.close()
			return nil, quarantineErr
		}
		if canonicalPresent && quarantinePresent {
			batch.close()
			return nil, fmt.Errorf("exclusive init retirement root and owned quarantine both exist: %s", plan.CaseRoot)
		}
		if quarantinePresent {
			if mode == ExclusiveInitRetirementFirst {
				batch.close()
				return nil, fmt.Errorf("exclusive init retirement first inspection rejects root quarantine: %s", plan.CaseRoot)
			}
			info = quarantineInfo
			item.rootName = item.rootQuarantine
			item.rootQuarantined = true
		} else if !canonicalPresent {
			if mode == ExclusiveInitRetirementFirst {
				batch.close()
				return nil, fmt.Errorf("exclusive init retirement first inspection requires root: %s", plan.CaseRoot)
			}
			continue
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			batch.close()
			return nil, fmt.Errorf("exclusive init retirement root is not a regular directory: %s", plan.CaseRoot)
		}
		item.root, err = item.parent.OpenRoot(item.rootName)
		if err != nil {
			batch.close()
			return nil, err
		}
		item.rootInfo, err = item.root.Stat(".")
		if err != nil || !os.SameFile(info, item.rootInfo) {
			batch.close()
			return nil, fmt.Errorf("exclusive init retirement root changed while opening: %s", plan.CaseRoot)
		}
		item.status.Present = true
		item.status.RemainingRoots = 1
		if err := inspectExclusiveInitRetirementRoot(item, mode); err != nil {
			batch.close()
			return nil, err
		}
	}
	return batch, nil
}

func openExclusiveInitRetirementParent(caseRoot string, mode ExclusiveInitRetirementMode) (*os.Root, string, string, error) {
	parentPath := filepath.Dir(caseRoot)
	parent, err := openExclusiveInitParent(parentPath)
	if err == nil {
		return parent, filepath.Base(caseRoot), "", nil
	}
	if mode != ExclusiveInitRetirementResume || !os.IsNotExist(err) {
		return nil, "", "", err
	}
	missingPath := parentPath
	for {
		ancestor := filepath.Dir(missingPath)
		if ancestor == missingPath {
			return nil, "", "", err
		}
		parent, openErr := openExclusiveInitParent(ancestor)
		if openErr == nil {
			rel, relErr := filepath.Rel(ancestor, caseRoot)
			if relErr != nil {
				_ = parent.Close()
				return nil, "", "", relErr
			}
			first, _, _ := strings.Cut(rel, string(filepath.Separator))
			return parent, first, first, nil
		}
		if !os.IsNotExist(openErr) {
			return nil, "", "", openErr
		}
		missingPath = ancestor
	}
}

func exclusiveInitRetirementRootsOverlap(left, right string) bool {
	if left == right {
		return true
	}
	separator := string(filepath.Separator)
	return strings.HasPrefix(left, right+separator) || strings.HasPrefix(right, left+separator)
}

func normalizeExclusiveInitRetirementPlan(plan ExclusiveInitRetirementPlan) (ExclusiveInitRetirementPlan, []string, error) {
	if plan.SchemaVersion != 1 || plan.Command != "exclusive-init-retirement" {
		return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("invalid exclusive init retirement plan identity")
	}
	caseFull, err := filepath.Abs(plan.CaseRoot)
	if err != nil || !casebind.SamePath(caseFull, plan.CaseRoot) {
		return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("invalid exclusive init retirement root: %s", plan.CaseRoot)
	}
	plan.CaseRoot = caseFull
	if strings.TrimSpace(plan.ProvisionID) == "" || strings.TrimSpace(plan.Role) == "" || len(plan.Leaves) == 0 {
		return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("exclusive init retirement plan is missing owner or leaves")
	}
	plan.Leaves = append([]ExclusiveInitRetirementLeaf(nil), plan.Leaves...)
	sort.Slice(plan.Leaves, func(i, j int) bool { return plan.Leaves[i].Path < plan.Leaves[j].Path })
	seen := map[string]struct{}{}
	dirSet := map[string]struct{}{}
	for i := range plan.Leaves {
		leaf := &plan.Leaves[i]
		rel, _, err := exclusiveInitPath(plan.CaseRoot, leaf.Path)
		if err != nil || rel != leaf.Path {
			return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("invalid exclusive init retirement leaf path: %q", leaf.Path)
		}
		key := strings.ToLower(rel)
		if _, ok := seen[key]; ok {
			return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("exclusive init retirement duplicate leaf: %s", rel)
		}
		seen[key] = struct{}{}
		if leaf.Size < 0 || len(leaf.SHA256) != sha256.Size*2 {
			return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("invalid exclusive init retirement content binding: %s", rel)
		}
		if _, err := hex.DecodeString(leaf.SHA256); err != nil || leaf.SHA256 != strings.ToLower(leaf.SHA256) {
			return ExclusiveInitRetirementPlan{}, nil, fmt.Errorf("invalid exclusive init retirement content hash: %s", rel)
		}
		for parent := path.Dir(rel); parent != "."; parent = path.Dir(parent) {
			dirSet[parent] = struct{}{}
		}
	}
	directories := make([]string, 0, len(dirSet))
	for dir := range dirSet {
		directories = append(directories, dir)
	}
	sort.Slice(directories, func(i, j int) bool {
		leftDepth := strings.Count(directories[i], "/")
		rightDepth := strings.Count(directories[j], "/")
		if leftDepth != rightDepth {
			return leftDepth > rightDepth
		}
		return directories[i] < directories[j]
	})
	return plan, directories, nil
}

func inspectExclusiveInitRetirementRoot(item *exclusiveInitRetirementRoot, mode ExclusiveInitRetirementMode) error {
	plannedLeaves := make(map[string]ExclusiveInitRetirementLeaf, len(item.plan.Leaves))
	plannedDirs := make(map[string]struct{}, len(item.directories))
	for _, leaf := range item.plan.Leaves {
		plannedLeaves[leaf.Path] = leaf
	}
	for _, dir := range item.directories {
		plannedDirs[dir] = struct{}{}
	}
	item.leafInfos = map[string]os.FileInfo{}
	item.leafQuarantineInfos = map[string]os.FileInfo{}
	item.dirInfos = map[string]os.FileInfo{}
	item.dirQuarantineInfos = map[string]os.FileInfo{}
	leafQuarantines := make(map[string]ExclusiveInitRetirementLeaf, len(item.plan.Leaves))
	dirQuarantines := make(map[string]string, len(item.directories))
	for _, leaf := range item.plan.Leaves {
		leafQuarantines[exclusiveInitRetirementLeafQuarantinePath(leaf)] = leaf
	}
	for _, dir := range item.directories {
		dirQuarantines[exclusiveInitRetirementDirectoryQuarantinePath(dir, item.plan)] = dir
	}
	err := fs.WalkDir(item.root.FS(), ".", func(rel string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if rel == "." {
			return nil
		}
		rel = path.Clean(rel)
		info, err := item.root.Lstat(filepath.FromSlash(rel))
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("exclusive init retirement rejects symlink: %s", rel)
		}
		if info.IsDir() {
			if _, ok := plannedDirs[rel]; ok {
				item.dirInfos[rel] = info
				return nil
			}
			if canonical, ok := dirQuarantines[rel]; ok {
				if mode == ExclusiveInitRetirementFirst {
					return fmt.Errorf("exclusive init retirement first inspection rejects directory quarantine: %s", canonical)
				}
				if err := verifyExclusiveInitRetirementEmptyDirectory(item.root, rel, info); err != nil {
					return err
				}
				item.dirQuarantineInfos[canonical] = info
				return fs.SkipDir
			}
			return fmt.Errorf("exclusive init retirement rejects extra directory: %s", rel)
		}
		leaf, ok := plannedLeaves[rel]
		if !ok {
			if canonical, owned := leafQuarantines[rel]; owned {
				if mode == ExclusiveInitRetirementFirst {
					return fmt.Errorf("exclusive init retirement first inspection rejects leaf quarantine: %s", canonical.Path)
				}
				if !info.Mode().IsRegular() {
					return fmt.Errorf("exclusive init retirement leaf quarantine is non-regular: %s", rel)
				}
				quarantineLeaf := canonical
				quarantineLeaf.Path = rel
				if err := verifyExclusiveInitRetirementLeaf(item.root, quarantineLeaf, nil); err != nil {
					return err
				}
				item.leafQuarantineInfos[canonical.Path] = info
				return nil
			}
			return fmt.Errorf("exclusive init retirement rejects extra object: %s", rel)
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("exclusive init retirement rejects non-regular object: %s", rel)
		}
		if err := verifyExclusiveInitRetirementLeaf(item.root, leaf, nil); err != nil {
			return err
		}
		item.leafInfos[rel] = info
		return nil
	})
	if err != nil {
		return err
	}
	for rel := range item.leafInfos {
		if _, ok := item.leafQuarantineInfos[rel]; ok {
			return fmt.Errorf("exclusive init retirement leaf and owned quarantine both exist: %s", rel)
		}
	}
	for rel := range item.dirInfos {
		if _, ok := item.dirQuarantineInfos[rel]; ok {
			return fmt.Errorf("exclusive init retirement directory and owned quarantine both exist: %s", rel)
		}
	}
	item.status.RemainingLeaves = len(item.leafInfos) + len(item.leafQuarantineInfos)
	item.status.RemainingDirectories = len(item.dirInfos) + len(item.dirQuarantineInfos)
	if mode == ExclusiveInitRetirementFirst {
		if item.rootQuarantined {
			return fmt.Errorf("exclusive init retirement first inspection rejects root quarantine: %s", item.plan.CaseRoot)
		}
		if len(item.leafInfos) != len(item.plan.Leaves) {
			return fmt.Errorf("exclusive init retirement first inspection requires complete leaves: %s", item.plan.CaseRoot)
		}
		if len(item.dirInfos) != len(item.directories) {
			return fmt.Errorf("exclusive init retirement first inspection requires complete directories: %s", item.plan.CaseRoot)
		}
	}
	return nil
}

func verifyExclusiveInitRetirementEmptyDirectory(root *os.Root, rel string, expected os.FileInfo) error {
	name := filepath.FromSlash(rel)
	before, err := root.Lstat(name)
	if err != nil || before.Mode()&os.ModeSymlink != 0 || !before.IsDir() || expected != nil && !os.SameFile(expected, before) {
		return fmt.Errorf("exclusive init retirement directory quarantine is non-directory or rebound: %s", rel)
	}
	dir, err := root.Open(name)
	if err != nil {
		return err
	}
	opened, statErr := dir.Stat()
	entries, readErr := dir.ReadDir(1)
	closeErr := dir.Close()
	if statErr != nil {
		return statErr
	}
	if readErr != nil && !errors.Is(readErr, io.EOF) {
		return readErr
	}
	if closeErr != nil {
		return closeErr
	}
	after, err := root.Lstat(name)
	if err != nil || !os.SameFile(before, opened) || !os.SameFile(opened, after) {
		return fmt.Errorf("exclusive init retirement directory quarantine identity changed: %s", rel)
	}
	if len(entries) != 0 {
		return fmt.Errorf("exclusive init retirement directory quarantine is not empty: %s", rel)
	}
	return nil
}

func retireExclusiveInitRetirementLeaf(root *os.Root, leaf ExclusiveInitRetirementLeaf, canonicalInfo, quarantineInfo os.FileInfo, caseRoot string) error {
	name := filepath.FromSlash(leaf.Path)
	quarantine := filepath.FromSlash(exclusiveInitRetirementLeafQuarantinePath(leaf))
	if canonicalInfo != nil {
		if quarantineInfo != nil {
			return fmt.Errorf("exclusive init retirement leaf and owned quarantine both exist: %s", leaf.Path)
		}
		if err := root.Rename(name, quarantine); err != nil {
			return fmt.Errorf("exclusive init retirement quarantine leaf %s: %w", leaf.Path, err)
		}
		quarantineInfo = canonicalInfo
		if err := verifyExclusiveInitRetirementLeaf(root, ExclusiveInitRetirementLeaf{Path: filepath.ToSlash(quarantine), SHA256: leaf.SHA256, Size: leaf.Size}, canonicalInfo); err != nil {
			return err
		}
		if exclusiveInitRetirementRemoveHook != nil {
			if err := exclusiveInitRetirementRemoveHook("after-leaf-quarantine", caseRoot, leaf.Path); err != nil {
				return err
			}
		}
		if err := syncExclusiveInitRetirementDirectory(root, filepath.Dir(name)); err != nil {
			return fmt.Errorf("exclusive init retirement sync leaf parent %s: %w", leaf.Path, err)
		}
	}
	if _, err := root.Lstat(name); !os.IsNotExist(err) {
		return fmt.Errorf("exclusive init retirement leaf name rebound: %s", leaf.Path)
	}
	if quarantineInfo == nil {
		return fmt.Errorf("exclusive init retirement leaf quarantine is missing: %s", leaf.Path)
	}
	if err := verifyExclusiveInitRetirementLeaf(root, ExclusiveInitRetirementLeaf{Path: filepath.ToSlash(quarantine), SHA256: leaf.SHA256, Size: leaf.Size}, quarantineInfo); err != nil {
		return err
	}
	if err := root.Remove(quarantine); err != nil {
		return fmt.Errorf("exclusive init retirement remove quarantined leaf %s: %w", leaf.Path, err)
	}
	if err := syncExclusiveInitRetirementDirectory(root, filepath.Dir(name)); err != nil {
		return fmt.Errorf("exclusive init retirement sync removed leaf parent %s: %w", leaf.Path, err)
	}
	return nil
}

func retireExclusiveInitRetirementDirectory(root *os.Root, rel string, canonicalInfo, quarantineInfo os.FileInfo, plan ExclusiveInitRetirementPlan) error {
	name := filepath.FromSlash(rel)
	quarantine := filepath.FromSlash(exclusiveInitRetirementDirectoryQuarantinePath(rel, plan))
	if canonicalInfo != nil {
		if quarantineInfo != nil {
			return fmt.Errorf("exclusive init retirement directory and owned quarantine both exist: %s", rel)
		}
		if err := root.Rename(name, quarantine); err != nil {
			return fmt.Errorf("exclusive init retirement quarantine directory %s: %w", rel, err)
		}
		quarantineInfo = canonicalInfo
		current, err := root.Lstat(quarantine)
		if err != nil || current.Mode()&os.ModeSymlink != 0 || !current.IsDir() || !os.SameFile(canonicalInfo, current) {
			return fmt.Errorf("exclusive init retirement quarantined directory identity changed: %s", rel)
		}
		if exclusiveInitRetirementRemoveHook != nil {
			if err := exclusiveInitRetirementRemoveHook("after-directory-quarantine", plan.CaseRoot, rel); err != nil {
				return err
			}
		}
		if err := syncExclusiveInitRetirementDirectory(root, filepath.Dir(name)); err != nil {
			return fmt.Errorf("exclusive init retirement sync directory parent %s: %w", rel, err)
		}
	}
	if _, err := root.Lstat(name); !os.IsNotExist(err) {
		return fmt.Errorf("exclusive init retirement directory name rebound: %s", rel)
	}
	if quarantineInfo == nil {
		return fmt.Errorf("exclusive init retirement directory quarantine is missing: %s", rel)
	}
	if err := verifyExclusiveInitRetirementEmptyDirectory(root, filepath.ToSlash(quarantine), quarantineInfo); err != nil {
		return err
	}
	if err := root.Remove(quarantine); err != nil {
		return fmt.Errorf("exclusive init retirement remove quarantined directory %s: %w", rel, err)
	}
	if err := syncExclusiveInitRetirementDirectory(root, filepath.Dir(name)); err != nil {
		return fmt.Errorf("exclusive init retirement sync removed directory parent %s: %w", rel, err)
	}
	return nil
}

func quarantineExclusiveInitRetirementRoot(root *exclusiveInitRetirementRoot) error {
	canonicalName := filepath.Base(root.plan.CaseRoot)
	quarantine := root.rootQuarantine
	if !root.rootQuarantined {
		if err := root.parent.Rename(canonicalName, quarantine); err != nil {
			return fmt.Errorf("exclusive init retirement quarantine root %s: %w", root.plan.CaseRoot, err)
		}
		root.rootName = quarantine
		root.rootQuarantined = true
		current, err := root.parent.Lstat(quarantine)
		opened, openErr := root.root.Stat(".")
		if err != nil || openErr != nil || current.Mode()&os.ModeSymlink != 0 || !current.IsDir() || !os.SameFile(root.rootInfo, current) || !os.SameFile(root.rootInfo, opened) {
			return fmt.Errorf("exclusive init retirement quarantined root identity changed: %s", root.plan.CaseRoot)
		}
		if exclusiveInitRetirementRemoveHook != nil {
			if err := exclusiveInitRetirementRemoveHook("after-root-quarantine", root.plan.CaseRoot, "."); err != nil {
				return err
			}
		}
		if err := syncExclusiveInitRetirementDirectory(root.parent, "."); err != nil {
			return fmt.Errorf("exclusive init retirement sync root parent %s: %w", root.plan.CaseRoot, err)
		}
	}
	if _, err := root.parent.Lstat(canonicalName); !os.IsNotExist(err) {
		return fmt.Errorf("exclusive init retirement root name rebound: %s", root.plan.CaseRoot)
	}
	current, err := root.parent.Lstat(quarantine)
	opened, openErr := root.root.Stat(".")
	if err != nil || openErr != nil || current.Mode()&os.ModeSymlink != 0 || !current.IsDir() || !os.SameFile(root.rootInfo, current) || !os.SameFile(root.rootInfo, opened) {
		return fmt.Errorf("exclusive init retirement quarantined root identity changed: %s", root.plan.CaseRoot)
	}
	if err := root.root.Close(); err != nil {
		return err
	}
	root.root = nil
	if err := root.parent.Remove(quarantine); err != nil {
		return fmt.Errorf("exclusive init retirement remove quarantined root %s: %w", root.plan.CaseRoot, err)
	}
	if err := syncExclusiveInitRetirementDirectory(root.parent, "."); err != nil {
		return fmt.Errorf("exclusive init retirement sync removed root parent %s: %w", root.plan.CaseRoot, err)
	}
	return nil
}

func exclusiveInitRetirementLeafQuarantinePath(leaf ExclusiveInitRetirementLeaf) string {
	name := filepath.FromSlash(leaf.Path)
	return filepath.ToSlash(filepath.Join(filepath.Dir(name), "."+filepath.Base(name)+".rekit-retire-leaf-"+leaf.SHA256[:16]+".tmp"))
}

func exclusiveInitRetirementDirectoryQuarantinePath(rel string, plan ExclusiveInitRetirementPlan) string {
	name := filepath.FromSlash(rel)
	sum := sha256.Sum256([]byte("directory\x00" + plan.ProvisionID + "\x00" + plan.Role + "\x00" + filepath.ToSlash(rel)))
	return filepath.ToSlash(filepath.Join(filepath.Dir(name), "."+filepath.Base(name)+".rekit-retire-dir-"+hex.EncodeToString(sum[:8])+".tmp"))
}

func exclusiveInitRetirementRootQuarantineName(name string, plan ExclusiveInitRetirementPlan) string {
	sum := sha256.Sum256([]byte("root\x00" + plan.ProvisionID + "\x00" + plan.Role + "\x00" + filepath.Clean(plan.CaseRoot)))
	return "." + name + ".rekit-retire-root-" + hex.EncodeToString(sum[:8]) + ".tmp"
}

func syncExclusiveInitRetirementDirectory(root *os.Root, name string) error {
	// Windows does not expose directory FlushFileBuffers through os.File.Sync;
	// Rename/Remove still provide namespace isolation, while Unix receives the
	// durability barrier needed for directory-entry ordering.
	if runtime.GOOS == "windows" {
		return nil
	}
	dir, err := root.Open(name)
	if err != nil {
		return err
	}
	if err := dir.Sync(); err != nil {
		_ = dir.Close()
		return err
	}
	return dir.Close()
}

func verifyExclusiveInitRetirementLeaf(root *os.Root, leaf ExclusiveInitRetirementLeaf, expected os.FileInfo) error {
	name := filepath.FromSlash(leaf.Path)
	before, err := root.Lstat(name)
	if err != nil {
		return err
	}
	if before.Mode()&os.ModeSymlink != 0 || !before.Mode().IsRegular() || expected != nil && !os.SameFile(expected, before) {
		return fmt.Errorf("exclusive init retirement leaf is non-regular or rebound: %s", leaf.Path)
	}
	file, err := root.Open(name)
	if err != nil {
		return err
	}
	opened, statErr := file.Stat()
	hash := sha256.New()
	read, readErr := io.Copy(hash, io.LimitReader(file, leaf.Size+1))
	closeErr := file.Close()
	if statErr != nil {
		return statErr
	}
	if readErr != nil {
		return readErr
	}
	if closeErr != nil {
		return closeErr
	}
	after, err := root.Lstat(name)
	if err != nil || !os.SameFile(before, opened) || !os.SameFile(opened, after) || read != leaf.Size || hex.EncodeToString(hash.Sum(nil)) != leaf.SHA256 {
		return fmt.Errorf("exclusive init retirement rejects different bytes or identity: %s", leaf.Path)
	}
	return nil
}

func validateExclusiveInitRetirementRootBinding(item *exclusiveInitRetirementRoot) error {
	if item.root == nil {
		return nil
	}
	canonical := filepath.Base(item.plan.CaseRoot)
	if item.rootQuarantined {
		if _, err := item.parent.Lstat(canonical); !os.IsNotExist(err) {
			return fmt.Errorf("exclusive init retirement root and owned quarantine both exist: %s", item.plan.CaseRoot)
		}
	} else if _, err := item.parent.Lstat(item.rootQuarantine); !os.IsNotExist(err) {
		return fmt.Errorf("exclusive init retirement root and owned quarantine both exist: %s", item.plan.CaseRoot)
	}
	leaf, leafErr := item.parent.Lstat(item.rootName)
	opened, rootErr := item.root.Stat(".")
	if leafErr != nil || rootErr != nil || leaf.Mode()&os.ModeSymlink != 0 || !leaf.IsDir() || !os.SameFile(item.rootInfo, leaf) || !os.SameFile(item.rootInfo, opened) {
		return fmt.Errorf("exclusive init retirement root identity changed: %s", item.plan.CaseRoot)
	}
	return nil
}

func (batch *exclusiveInitRetirementBatch) bindCommonParent(expected os.FileInfo) error {
	var common os.FileInfo
	for i := range batch.roots {
		item := &batch.roots[i]
		if item.absentBoundary != "" {
			return fmt.Errorf("exclusive init retirement parent binding requires direct root parent: %s", item.plan.CaseRoot)
		}
		info, err := item.parent.Stat(".")
		if err != nil || !os.SameFile(expected, info) {
			return fmt.Errorf("exclusive init retirement parent identity mismatch: %s", item.plan.CaseRoot)
		}
		if common == nil {
			common = info
		} else if !os.SameFile(common, info) {
			return fmt.Errorf("exclusive init retirement batch parents have different identities")
		}
	}
	return nil
}

func (batch *exclusiveInitRetirementBatch) revalidate() error {
	for i := range batch.roots {
		item := &batch.roots[i]
		if !item.status.Present {
			if item.absentBoundary != "" {
				if _, err := item.parent.Lstat(item.absentBoundary); !os.IsNotExist(err) {
					return fmt.Errorf("exclusive init retirement absent boundary rebound: %s", item.plan.CaseRoot)
				}
			} else {
				canonical := filepath.Base(item.plan.CaseRoot)
				if _, err := item.parent.Lstat(canonical); !os.IsNotExist(err) {
					return fmt.Errorf("exclusive init retirement absent root rebound: %s", item.plan.CaseRoot)
				}
				if _, err := item.parent.Lstat(item.rootQuarantine); !os.IsNotExist(err) {
					return fmt.Errorf("exclusive init retirement absent root quarantine rebound: %s", item.plan.CaseRoot)
				}
			}
			continue
		}
		if err := validateExclusiveInitRetirementRootBinding(item); err != nil {
			return err
		}
		current := exclusiveInitRetirementRoot{
			plan:        item.plan,
			root:        item.root,
			directories: item.directories,
		}
		if err := inspectExclusiveInitRetirementRoot(&current, ExclusiveInitRetirementResume); err != nil {
			return err
		}
		if err := compareExclusiveInitRetirementObjectIdentities(item, &current); err != nil {
			return err
		}
	}
	return nil
}

func compareExclusiveInitRetirementObjectIdentities(expected, current *exclusiveInitRetirementRoot) error {
	if len(expected.leafInfos) != len(current.leafInfos) || len(expected.leafQuarantineInfos) != len(current.leafQuarantineInfos) || len(expected.dirInfos) != len(current.dirInfos) || len(expected.dirQuarantineInfos) != len(current.dirQuarantineInfos) {
		return fmt.Errorf("exclusive init retirement object set changed: %s", expected.plan.CaseRoot)
	}
	if err := compareExclusiveInitRetirementInfoMap("leaf", expected.leafInfos, current.leafInfos); err != nil {
		return err
	}
	if err := compareExclusiveInitRetirementInfoMap("leaf quarantine", expected.leafQuarantineInfos, current.leafQuarantineInfos); err != nil {
		return err
	}
	if err := compareExclusiveInitRetirementInfoMap("directory", expected.dirInfos, current.dirInfos); err != nil {
		return err
	}
	return compareExclusiveInitRetirementInfoMap("directory quarantine", expected.dirQuarantineInfos, current.dirQuarantineInfos)
}

func compareExclusiveInitRetirementInfoMap(kind string, expected, current map[string]os.FileInfo) error {
	for rel, expectedInfo := range expected {
		currentInfo, ok := current[rel]
		if !ok || !os.SameFile(expectedInfo, currentInfo) {
			return fmt.Errorf("exclusive init retirement %s identity changed: %s", kind, rel)
		}
	}
	return nil
}

func (batch *exclusiveInitRetirementBatch) inspection() ExclusiveInitRetirementInspection {
	result := ExclusiveInitRetirementInspection{
		SchemaVersion: 1,
		Command:       "exclusive-init-retirement",
		Mode:          batch.mode,
		Roots:         make([]ExclusiveInitRetirementRootInspection, 0, len(batch.roots)),
	}
	var commonInfo os.FileInfo
	for i := range batch.roots {
		status := batch.roots[i].status
		result.Roots = append(result.Roots, status)
		if batch.roots[i].absentBoundary == "" {
			if info, err := batch.roots[i].parent.Stat("."); err == nil {
				if commonInfo == nil {
					commonInfo = info
					result.CommonParent = filepath.Dir(batch.roots[i].plan.CaseRoot)
					result.CommonParentIdentity = true
				} else if !os.SameFile(commonInfo, info) {
					result.CommonParent = ""
					result.CommonParentIdentity = false
				}
			}
		} else {
			result.CommonParent = ""
			result.CommonParentIdentity = false
		}
		result.RemainingLeaves += status.RemainingLeaves
		result.RemainingDirectories += status.RemainingDirectories
		result.RemainingRoots += status.RemainingRoots
	}
	return result
}

func (batch *exclusiveInitRetirementBatch) close() error {
	if batch == nil {
		return nil
	}
	var closeErr error
	for i := len(batch.roots) - 1; i >= 0; i-- {
		if batch.roots[i].root != nil {
			closeErr = errors.Join(closeErr, batch.roots[i].root.Close())
			batch.roots[i].root = nil
		}
		if batch.roots[i].parent != nil {
			closeErr = errors.Join(closeErr, batch.roots[i].parent.Close())
			batch.roots[i].parent = nil
		}
	}
	return closeErr
}
