package caseshim

import (
	"fmt"

	"github.com/shuiyu486/re-context-kits/internal/rekit/defaults"
	"github.com/shuiyu486/re-context-kits/internal/rekit/packidentity"
)

// Trusted recovery hashes are append-only sets. Current pack-generation
// invariants ensure today's generated bytes remain represented while older
// pending onboarding intents stay recoverable after future pack revisions.
var acceptedManagedBlockSHA256 = map[string]map[string]struct{}{
	"_template":                 {"a425c88cfdff2fd66358777c0aec41b0bfe8a0cfc7f3e8b98edd45795ee7a54b": {}},
	defaults.DefaultPack:        {"f12e9febbf923f815f1113f48b2b31e20137a77fb640a12db341dac9e8e4988e": {}, "3230948002ebeefb79f7e233bccc4b23fbad0048588bd3cc99375de7724cd57d": {}, "009394f5e368588bf89eca48c78ec1e6aeeaeb23ce0f63bc0fc4dc81221d2718": {}, "0dfb64144dd593183646fd041a189901650b8aac28c0e8375e2b9a7485a767a8": {}},
	"web-security":              {"7eef51aaab24e7900161ab973245493540d49acb7dca4ff169c6aff9b22a0aa5": {}, "aea88ea6987b8181d7dae7378569e012eae1929d428c0d2b9995bf02eb07e1aa": {}},
	"malware-analysis":          {"19a212821fb415c700cd35af71874ac1d2b029e11c76d8b129bae5e6b95b3b3e": {}},
	"vuln-research":             {"292d2289e79128fef5815943cc5ea5680c668859fc89468a16e2249746de2ddb": {}},
	"ctf":                       {"72a2f68b245dfedc6bea40c013ccc21b72ae251d1e48ec349e34dff9eace87b0": {}},
	"unpack-pe":                 {"b4a965275e4d6c9d0f19228cba4587cbd8e724cb072236fd22f26ceb75ebeb80": {}},
	"ollvm":                     {"79b570b0d5093ce33825d7e7acf8a044437fbbdb1ec66d739bc15cc7f4ab3a94": {}},
	"android-native":            {"e492d274ec3e6ac8798e877d844b64cc2b22b130d197b98f259109b037bf765a": {}},
	packidentity.RetiredGeneric: {"791bdef68910f51acd810c60a322ff2ee5624a0598290e2a6f619eb0a3f92bb1": {}},
	packidentity.RetiredVMP:     {"f12e9febbf923f815f1113f48b2b31e20137a77fb640a12db341dac9e8e4988e": {}},
}

var acceptedSupportSHA256 = map[string]map[string]map[string]struct{}{
	defaults.DefaultPack:    {".gitignore": {"1f2e0c6e920633ca91511262703bb5e9c00ddc74657b0a7fd21ea372bc8fef96": {}}},
	packidentity.RetiredVMP: {".gitignore": {"1f2e0c6e920633ca91511262703bb5e9c00ddc74657b0a7fd21ea372bc8fef96": {}}},
}

func ValidateManagedBlockSHA256(pack, sum string) error {
	if _, ok := acceptedManagedBlockSHA256[pack][sum]; !ok {
		return fmt.Errorf("managed block does not match an accepted trusted pack generation")
	}
	return nil
}

func ExpectedSupportPaths(pack string) []string {
	paths := make([]string, 0, len(acceptedSupportSHA256[pack]))
	for path := range acceptedSupportSHA256[pack] {
		paths = append(paths, path)
	}
	return paths
}

func ValidateSupportSHA256(pack, path, sum string) error {
	if _, ok := acceptedSupportSHA256[pack][path][sum]; !ok {
		return fmt.Errorf("support file does not match an accepted trusted pack generation")
	}
	return nil
}
